export const cardupgradeAbi: any = [
  {
    inputs: [
      { internalType: 'address', name: '_treasury', type: 'address' },
      { internalType: 'address', name: '_priceConsumer', type: 'address' },
    ],
    stateMutability: 'nonpayable',
    type: 'constructor',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_index',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: '_is4PlayFixedPrice',
        type: 'bool',
      },
      {
        indexed: false,
        internalType: 'address',
        name: '_cardContract',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_legendaryCardId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_maxLimit',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_lockPeriod',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_priceInStable',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_priceIn4Play',
        type: 'uint256',
      },
    ],
    name: 'AddNewGameCard',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: '_is4PlayFixedPrice',
        type: 'bool',
      },
    ],
    name: 'Change4PlayFixedPrice',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_discount',
        type: 'uint256',
      },
    ],
    name: 'ChangeDiscount',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_lockPeriod',
        type: 'uint256',
      },
    ],
    name: 'ChangeLockPeriod',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_limit',
        type: 'uint256',
      },
    ],
    name: 'ChangeMaxLimit',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'bool',
        name: '_isUpgradeable',
        type: 'bool',
      },
    ],
    name: 'ManageCollection',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: 'address',
        name: 'previousOwner',
        type: 'address',
      },
      {
        indexed: true,
        internalType: 'address',
        name: 'newOwner',
        type: 'address',
      },
    ],
    name: 'OwnershipTransferred',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'Paused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_price',
        type: 'uint256',
      },
    ],
    name: 'SetCardsPriceIn4Play',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_price',
        type: 'uint256',
      },
    ],
    name: 'SetCardsPriceInStable',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_treasury',
        type: 'address',
      },
    ],
    name: 'SetTreasury',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'uint256',
        name: '_fee',
        type: 'uint256',
      },
    ],
    name: 'SetUnLockfeeIn4Play',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_cardId',
        type: 'uint256',
      },
    ],
    name: 'UnLockCardAfterLockEnd',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_cardId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
    ],
    name: 'UnLockCardBeforeLockEnd',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: 'account',
        type: 'address',
      },
    ],
    name: 'Unpaused',
    type: 'event',
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: 'address',
        name: '_account',
        type: 'address',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_gameId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_cardId',
        type: 'uint256',
      },
      {
        indexed: false,
        internalType: 'uint256',
        name: '_amount',
        type: 'uint256',
      },
    ],
    name: 'UpgradeToken',
    type: 'event',
  },
  {
    inputs: [],
    name: 'DENOMINATOR',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT4Play',
    outputs: [{ internalType: 'contract IERC20', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'NFT4Play_eth_Pair',
    outputs: [{ internalType: 'contract SwapPair', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'PriceConsumer',
    outputs: [{ internalType: 'contract Consumer', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_cardContract', type: 'address' },
      { internalType: 'uint256', name: '_legendaryCardId', type: 'uint256' },
      { internalType: 'uint256', name: '_maxLimit', type: 'uint256' },
      { internalType: 'uint256', name: '_lockPeriod', type: 'uint256' },
      { internalType: 'uint256', name: '_priceInStable', type: 'uint256' },
      { internalType: 'uint256', name: '_priceIn4Play', type: 'uint256' },
      { internalType: 'bool', name: '_is4PlayFixedPrice', type: 'bool' },
    ],
    name: 'addNewGameCard',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'bool', name: '_is4PlayFixedPrice', type: 'bool' },
    ],
    name: 'change4PlayFixedPrice',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_discount', type: 'uint256' }],
    name: 'changeDiscount',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'uint256', name: '_lockPeriod', type: 'uint256' },
    ],
    name: 'changeLockPeriod',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'uint256', name: '_limit', type: 'uint256' },
    ],
    name: 'changeMaxLimit',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'bool', name: '_state', type: 'bool' }],
    name: 'changePairState',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'differentPair',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'discount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_gameId', type: 'uint256' }],
    name: 'getGameInfo',
    outputs: [
      {
        components: [
          { internalType: 'bool', name: 'isUpgradeable', type: 'bool' },
          { internalType: 'bool', name: 'is4PlayFixedPrice', type: 'bool' },
          {
            internalType: 'address',
            name: 'collectionAddress',
            type: 'address',
          },
          { internalType: 'uint256', name: 'maxLimit', type: 'uint256' },
          { internalType: 'uint256', name: 'legendaryCardId', type: 'uint256' },
          { internalType: 'uint256', name: 'lockPeriod', type: 'uint256' },
          {
            internalType: 'uint256',
            name: 'upgardePiceInStable',
            type: 'uint256',
          },
          {
            internalType: 'uint256',
            name: 'upgradePiceIn4Play',
            type: 'uint256',
          },
        ],
        internalType: 'struct CardUpgrade.Game',
        name: '',
        type: 'tuple',
      },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'address', name: '_user', type: 'address' },
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
    ],
    name: 'getUserInfo',
    outputs: [
      { internalType: 'uint256[]', name: '', type: 'uint256[]' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'isCardListed',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'bool', name: '_isUpgradeable', type: 'bool' },
    ],
    name: 'manageCollection',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'nft4PlayInDollor',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'owner',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'pause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'paused',
    outputs: [{ internalType: 'bool', name: '', type: 'bool' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_gameId', type: 'uint256' }],
    name: 'payableAmount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'renounceOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_nft4Play', type: 'address' }],
    name: 'set4PlayToken',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
    ],
    name: 'setCardsPriceIn4Play',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'uint256', name: '_price', type: 'uint256' },
    ],
    name: 'setCardsPriceInStable',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_pair', type: 'address' }],
    name: 'setPairAddress',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '_treasury', type: 'address' }],
    name: 'setTreasury',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'uint256', name: '_fee', type: 'uint256' }],
    name: 'setUnLockfeeIn4Play',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'tokenOwners',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'tokenUnlockTime',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '', type: 'uint256' },
      { internalType: 'uint256', name: '', type: 'uint256' },
    ],
    name: 'tokenUpdateCount',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'totalListedGame',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: 'newOwner', type: 'address' }],
    name: 'transferOwnership',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'treasury',
    outputs: [{ internalType: 'address', name: '', type: 'address' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'uint256', name: '_cardId', type: 'uint256' },
    ],
    name: 'unLockCardAfterLockEnd',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'uint256', name: '_cardId', type: 'uint256' },
    ],
    name: 'unLockCardBeforeLockEnd',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [],
    name: 'unLockFeeIn4Play',
    outputs: [{ internalType: 'uint256', name: '', type: 'uint256' }],
    stateMutability: 'view',
    type: 'function',
  },
  {
    inputs: [],
    name: 'unpause',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [
      { internalType: 'uint256', name: '_gameId', type: 'uint256' },
      { internalType: 'uint256', name: '_cardId', type: 'uint256' },
      { internalType: 'bool', name: '_unLock', type: 'bool' },
    ],
    name: 'upgradeCard',
    outputs: [],
    stateMutability: 'nonpayable',
    type: 'function',
  },
  {
    inputs: [{ internalType: 'address', name: '', type: 'address' }],
    name: 'userInfo',
    outputs: [
      { internalType: 'uint256', name: 'amountStaked', type: 'uint256' },
    ],
    stateMutability: 'view',
    type: 'function',
  },
]
